### ISSUE TITLE
Rename vfredsum and vfwredsum to vfredusum and vfwredusum to match 1.0 spec

### ISSUE THREAD

**Issue by topperc** [riscv-non-isa/rvv-intrinsic-doc#100]
These were rename to include "u" for unordered

**Comment by Hsiangkai** [comment]
Should we add a tag for v0.10?

**Comment by zakk0610** [comment]
we already have [v0.10 ](https://github.com/riscv/rvv-intrinsic-doc/releases/tag/v0.10 )tag

**Comment by zakk0610** [comment]
https://github.com/riscv-non-isa/rvv-intrinsic-doc/commit/dc1a3f0c2691cd4c5270d8010efaa30a8a366653
