### ISSUE TITLE
Broken links and missing rvv_intrinsic_gen.py and misc inconsistencies

### ISSUE THREAD

**Issue by jim-wilson** [riscv-non-isa/rvv-intrinsic-doc#105]
The files in the intrinsic_functions dir claim that they were generated by rvv_intrinsic_gen.py but I can find no such file.  I checked multiple riscv github trees and multiple compiler source trees.  It shouldn't be this hard to find it.

Most of the links between rvv-instrinsic-api.md and the intrinsic_functions/* files are broken.  Looks like the old file 04_* disappeared.  Also, the section labels in the instrinsic_functions files now have section numbers prepended.  And most (but not all) section labels changed -functions to -operations.  None of these changes are reflected in the rvv-instrinsics-api.md file.

I have a patch that mostly fixes this, except I ran into too many inconsistencies that I can't fix without the missing rvv_intrinsic_gen.py file and some discussion.

There are duplicate labels.  For instance
```
rohan:2097$ grep '###' * | grep 'unit-stride-op'
02_vector_loads_and_stores_functions.md:### [Vector Unit-Stride Load Functions](../rvv-intrinsic-api.md#74-vector-unit-stride-operations):
02_vector_loads_and_stores_functions.md:### [Vector Unit-Stride Store Functions](../rvv-intrinsic-api.md#74-vector-unit-stride-operations):
rohan:2098$ 
```
and
```
rohan:2071$ grep '###' * | grep loadstore
02_vector_loads_and_stores_functions.md:### [Vector Strided Load Functions](../rvv-intrinsic-api.md#75-vector-strided-loadstore-operations):
02_vector_loads_and_stores_functions.md:### [Vector Strided Store Functions](../rvv-intrinsic-api.md#75-vector-strided-loadstore-operations):
02_vector_loads_and_stores_functions.md:### [Vector Indexed Load Functions](../rvv-intrinsic-api.md#76-vector-indexed-loadstore-operations):
02_vector_loads_and_stores_functions.md:### [Vector Indexed Store Functions](../rvv-intrinsic-api.md#76-vector-indexed-loadstore-operations):
rohan:2072$ 
```
but rvv-intrinsic-api.md expects load and store to have separate labels.

Also, there is confusion with binary and unary bitwise operations which have the same section label.
```
rohan:2077$ grep '###' * | grep bitwise-logical
05_vector_integer_arithmetic_functions.md:### [Vector Bitwise Logical Functions](../rvv-intrinsic-api.md#125-vector-bitwise-logical-operations):
05_vector_integer_arithmetic_functions.md:### [Vector Bitwise Logical Functions](../rvv-intrinsic-api.md#125-vector-bitwise-logical-operations):
rohan:2078$ 
```

There are missing labels.  For instance
```
rohan:2072$ grep '###' * | grep '()'
03_vector_load_store_segment_instructions_zvlsseg.md:### [Vector Unit-Stride Segment Load Functions]():
03_vector_load_store_segment_instructions_zvlsseg.md:### [Vector Unit-Stride Segment Store Functions]():
03_vector_load_store_segment_instructions_zvlsseg.md:### [Vector Strided Segment Load Functions]():
03_vector_load_store_segment_instructions_zvlsseg.md:### [Vector Strided Segment Store Functions]():
03_vector_load_store_segment_instructions_zvlsseg.md:### [Vector Indexed Segment Load Functions]():
03_vector_load_store_segment_instructions_zvlsseg.md:### [Vector Indexed Segment Store Functions]():
rohan:2073$ 
```

There are section labels with corrupted back pointers.

```
rohan:2084$ grep '###' * | grep -v '()' | grep -v 'md#'
11_miscellaneous_vector_functions.md:### [Vector LMUL Extension Functions](../rvv-intrinsic-api.mdvector-lmul-extension-and-truncation-functions):
11_miscellaneous_vector_functions.md:### [Vector LMUL Truncation Functions](../rvv-intrinsic-api.mdvector-lmul-extension-and-truncation-functions):
rohan:2085$ 
```
This is also yet another duplicate label.

And while most labels had the "-functions" changed to "-operations", some still say -operations, and some now say neither, they just lost their suffix.  This can be handled without broken links.  This is just more of a quality-of-implementation issue as the naming differences make it harder to maintain the docs.
```
rohan:2091$ grep '###' * | grep -v '()' | grep -- -operations | wc
     58     320    9346
rohan:2092$ grep '###' * | grep -v '()' | grep -- -functions | wc
      8      39    1113
rohan:2093$ grep '###' * | grep -v '()' | grep -v -- -functions | grep -v -- -operations | wc
     14      86    1979
rohan:2094$ 
```

There are also section labels that are in the intrisics files but not referenced in the rvv-vector-api.md file.
```
11_miscellaneous_vector_functions.md:### [Vector Insertion Functions](../rvv-intrinsic-api.md#vector-insertion-functions):
11_miscellaneous_vector_functions.md:### [Vector Extraction Functions](../rvv-intrinsic-api.md#vector-extration-functions):
```
Also, extraction is misspelled here.

The labels that start with a number aren't working for me.  They go to the right file, but not the right label inside that file.  It isn't obvious what is wrong, but maybe they aren't being parsed as intended.  The labels that don't start with numbers do work.

**Comment by eopXD** [comment]
This is part of our release milestone to open-source the intrinsic generator in SiFive. We will resolve this in the v1.0 release.
