### ISSUE TITLE
Is there any good pdf presentation for this project?

### ISSUE THREAD

**Issue by Geng-Qi-alibaba** [riscv-non-isa/rvv-intrinsic-doc#108]
I did not find instructions on how to generate a pdf. So, I tried myself,
However, the resulting pdf is not easy to read, as the content is divided into different files.

I just want a single pdf file with information that is relatively complete. Is there any way? And how should I do it?

**Comment by eopXD** [comment]
This is part of our release milestone to release a better-printed document of the RVV C Intrinsic API. We will resolve this in this v1.0 release.
