### ISSUE TITLE
Errors when ugin 

### ISSUE THREAD

**Issue by yoshinori-watanabe-nsitexe** [riscv-non-isa/rvv-intrinsic-doc#119]
When using vrgatherei16_vv_f64m1 and  vrgatherei16_vv_f64m2
defined in https://github.com/riscv-non-isa/rvv-intrinsic-doc/blob/master/intrinsic_funcs/10_vector_permutation_functions.md#174-vector-register-gather-operations

,
![image](https://user-images.githubusercontent.com/72848183/135981290-72d77e78-61c1-49f9-b9f0-209ab4652b06.png)

Following compile errors occur with riscv gcc rvv-intrinsic ( https://github.com/riscv-collab/riscv-gnu-toolchain/tree/rvv-intrinsic ).

~~~
error: 'vuint16mf4_t' was not declared in this scope; did you mean 'vuint16m4_t'?
|           vuint16mf4_t   v_slideindex0;
|         ^~~~~~~~~~~~
|           vuint16m4_t
~~~

~~~
error: 'vuint16mf2_t' was not declared in this scope; did you mean 'vuint16m2_t'?
 |         vuint16mf2_t v_slideindex0;
 |         ^~~~~~~~~~~~
 |         vuint16m2_t
~~~

Are these variable types valid with LMUL<1 ?

**Comment by Hsiangkai** [comment]
https://godbolt.org/z/hdoaKjq47
