### ISSUE TITLE
Propose a new set of intrinsics considering tail and mask agnostic/undisturbed policy.

### ISSUE THREAD

**Issue by Hsiangkai** [riscv-non-isa/rvv-intrinsic-doc#120]
In PR #101, we propose `_mt` intrinsics to introduce tail policy argument without adding too many intrinsics. However, there are several problems in the design.

* There is no intrinsic for tu,ma combination.
* There is no intrinsic for ta,ma for multiply-add intrinsics because the destination of multiply-add could not be vundefined().
* We use all-one mask and vundefined() to control the tail/mask policy. It is not an obvious way for users.
* The code gen quality is not good for unmasked tail undisturbed intrinsics.

For the last point, we propose PR #116 to introduce `_tu` variant for unmasked intrinsics.

There are two styles in the current intrinsics. For unmasked ones, we append the suffix `_tu` to control the policy. For masked ones, we use the additional `ta` argument plus some implication rules to control the policy.

Ideally, we should make the design consistent. So, we are thinking about to append {tu/ta}, {mu/ma} to the intrinsic names. There are some reasons to do it.

* {tu/ta}, {mu/ma} are parts of vtype. We already encode part of the vtype, e.g., i8m1, into the intrinsic names. It makes sense to encode {tu/ta}, {mu/ma} in the intrinsic names.
* It is apparent to users to use it. There is no implication rules for all-one mask and maskedoff == vundefined().
* It makes the design consistent between masked and unmasked intrinsics.

The only problem of the proposal is it will bring a whole bunch set of intrinsics. However, if we could reduce the header size of intrinsics. It should not be a serious problem. From https://reviews.llvm.org/D103228. It should be a solvable problem.

So, we propose the following new set of intrinsics for tail/mask policy.

Masked? | TU? | MU? | Intrinsic
---|---|---|---
No | No | N/A | `vadd_vv_i8m1_ta(vs2, vs1, vl)` and `vadd_vv_i8m1(vs2, vs1, vl)`<sup>1</sup>
No | Yes | N/A | `vadd_vv_i8m1_tu(merge,vs2, vs1, vl)`
Yes | No | No | `vadd_vv_i8m1_tama(mask, vs2, vs1, vl)`
Yes | No | Yes | `vadd_vv_i8m1_tamu(mask, merge, vs2, vs1, vl)`
Yes | Yes | No | `vadd_vv_i8m1_tuma(mask, merge, vs2, vs1, vl)`
Yes | Yes | Yes | `vadd_vv_i8m1_tumu(mask, merge, vs2, vs1, vl)` and `vadd_vv_i8m1_m(mask, merge, vs2, vs1, vl)`<sup>1</sup>

For multiply-add intrinsics or other intrinsics with the destination argument.

Masked? | TU? | MU? | Intrinsic
---|---|---|---
No | No | N/A | `vmacc_vv_i8m1_ta(vd, vs1, vs2, vl)`
No | Yes | N/A | `vmacc_vv_i8m1_tu(vd, vs1, vs2, vl)` and `vmacc_vv_i8m1(vd, vs1, vs2, vl)`<sup>1</sup>
Yes | No | No | `vmacc_vv_i8m1_tama(mask, vd, vs1, vs2, vl)`
Yes | No | Yes | `vmacc_vv_i8m1_tamu(mask, vd, vs1, vs2, vl)`
Yes | Yes | No | `vmacc_vv_i8m1_tuma(mask, vd, vs1, vs2, vl)`
Yes | Yes | Yes | `vmacc_vv_i8m1_tumu(mask, vd, vs1, vs2, vl)` and `vmacc_vv_i8m1_m(mask, vd, vs1, vs2, vl)`<sup>1</sup>

<sup>1</sup> For backward compatibility before v0.10 intrinsics. The problem is whether we should support these intrinsics for long run or we should deprecate these intrinsics one day. If we should deprecate these intrinsics, we may need to issue warnings to users to avoid using them in the future.

**Comment by kuanlinchentw** [comment]
May I ask how many of the new tail/mask types will support overloaded intrinsic functions. Thanks.

**Comment by zakk0610** [comment]
There are other cases that have not mention above:
Some cases like vector reduction or vslideup/vslidedown operations which do not need to have destination argument in `ta` and `tama`.

Masked? | TU? | MU? | Intrinsic
---|---|---|---
No | No | N/A | `redsum_vs_i8m1_ta(vs1, vs2, vl)`
No | Yes | N/A | `redsum_vs_i8m1_tu(vd, vs1, vs2, vl)` and `redsum_vs_i8m1(vd, vs1, vs2, vl)`<sup>1</sup>
Yes | No | No | `redsum_vs_i8m1_tama(mask, vs1, vs2, vl)`
Yes | No | Yes | `redsum_vs_i8m1_tamu(mask, vd, vs1, vs2, vl)`
Yes | Yes | No | `redsum_vs_i8m1_tuma(mask, vd, vs1, vs2, vl)`
Yes | Yes | Yes | `redsum_vs_i8m1_tumu(mask, vd, vs1, vs2, vl)` and `redsum_vs_i8m1_m(mask, vd, vs1, vs2, vl)`

@kuanlinchentw I think we could encode the policy in the end of function name, what do you think?
For example, vadd would have vadd_ta, vadd_tu, vadd_tama, vadd_tamu, vadd_tuma, vadd_tumu.

**Comment by kuanlinchentw** [comment]
It's fine with me. Thanks.

**Comment by lhtin** [comment]
I have a question about this new intrinsic design. For example, for the vadd intrinsics without the mask, what is the mean of `N/A` of the `MU?` row. Does that mean leaving the decision to the compiler? Why not let the users of intrinsics decide?

**Comment by zakk0610** [comment]
Compiler can help on choosing the best mask policy for nomask operations to reduce vsetvli instruction.
IMO, asking users to give the mask policy for nomask operations, it does not make sense to me.

**Comment by lhtin** [comment]
Another question is: From the [RISCV Spec 1.0](https://github.com/riscv/riscv-v-spec/blob/master/v-spec.adoc#vector-integer-compare-instructions), It says "Compares write mask registers, and so always operate under a tail-agnostic policy." So is there have `vmseq_vv_i8m1_b8_tu` intrinsic?

**Comment by lhtin** [comment]
> Compiler can help on choosing the best mask policy for nomask operations to reduce vsetvli instruction. IMO, asking users to give the mask policy for nomask operations, it does not make sense to me.

Thanks for your prompt answer. I agree with you.

**Comment by kito-cheng** [comment]
> So is there have vmseq_vv_i8m1_b8_tu intrinsic?
We won't have _tu intrinsic for compare instruction or mask instructions, Spec say "Compares write mask registers, and so always operate under a tail-agnostic policy." [1] and "the tail elements, are always updated with a tail-agnostic policy." for  mask instruction [2].

[1] https://github.com/riscv/riscv-v-spec/blob/master/v-spec.adoc#118-vector-integer-compare-instructions
[2] https://github.com/riscv/riscv-v-spec/blob/master/v-spec.adoc#15-vector-mask-instructions

**Comment by lhtin** [comment]
> We won't have _tu intrinsic for compare instruction or mask instructions

Is there also no _ta intrinsic? That is to say, only have vmseq_vv_i8m1_b8 for nomask operation and leaving the decision of vsetvl's tail policy to the compiler?

**Comment by lhtin** [comment]
From my current understanding, I enumerate the possible cases for intrinsics. Can you help me with a review to see if there are any omissions or misunderstandings? Thanks.

- mask policy and tail policy
  - 7\. Vector load
    - except mask load（vlm）
  - 11.1. Vector Single-Width Integer Add and Subtract
  - 11.2. Vector Widening Integer Add/Subtract
  - 11.3. Vector Integer Extension
  - 11.4. Vector Integer Add-with-Carry / Subtract-with-Borrow Instructions
  - 11.5. Vector Bitwise Logical Instructions
  - 11.6. Vector Single-Width Shift Instructions
  - 11.7. Vector Narrowing Integer Right Shift Instructions
  - 11.9. Vector Integer Min/Max Instructions
  - 11.10. Vector Single-Width Integer Multiply Instructions
  - 11.11. Vector Integer Divide Instructions
  - 11.12. Vector Widening Integer Multiply Instructions
  - 12.1. Vector Single-Width Saturating Add and Subtract
  - 12.2. Vector Single-Width Averaging Add and Subtract
  - 12.3. Vector Single-Width Fractional Multiply with Rounding and Saturation
  - 12.4. Vector Single-Width Scaling Shift Instructions
  - 12\. Vector Fixed-Point Arithmetic Instructions
  - 13\. Vector Floating-Point Instructions
    - except 13.13, 13.15, 13.16
  - 14\. Vector Reduction Operations
  - 15.8. Vector Iota Instruction ???
  - 15.9. Vector Element Index Instruction
  - 16.3. Vector Slide Instructions
  - 16.4. Vector Register Gather Instructions

  | Masked? | TU? | MU? | Intrinsic |
  | ------- | --- | --- | --------- |
  | No      | No  | N/A | vadd_vv_i8m1_ta(vs2, vs1, vl)<br>vadd_vv_i8m1(vs2, vs1, vl)<sup>1</sup> |
  | No      | Yes | N/A | vadd_vv_i8m1_tu(vd, vs2, vs1, vl) |
  | Yes     | No  | No  | vadd_vv_i8m1_tama(mask, vs2, vs1, vl) |
  | Yes     | No  | Yes | vadd_vv_i8m1_tamu(mask, vd, vs2, vs1, vl) |
  | Yes     | Yes | No  | vadd_vv_i8m1_tuma(mask, vd, vs2, vs1, vl) |
  | Yes     | Yes | Yes | vadd_vv_i8m1_tumu(mask, vd, vs2, vs1, vl)<br>vadd_vv_i8m1_m(mask, vd, vs2, vs1, vl)<sup>1</sup> |

- mask policy and tail policy and vd get involved
  - 11.13. Vector Single-Width Integer Multiply-Add Instructions
  - 11.14. Vector Widening Integer Multiply-Add Instructions

  | Masked? | TU? | MU? | Intrinsic |
  | ------- | --- | --- | --------- |
  | No      | No  | N/A | vmacc_vv_i8m1_ta(vd, vs1, vs2, vl) |
  | No      | Yes | N/A | vmacc_vv_i8m1_tu(vd, vs1, vs2, vl)<br>vmacc_vv_i8m1(vd, vs1, vs2, vl)<sup>1</sup> |
  | Yes     | No  | No  | vmacc_vv_i8m1_tama(mask, vd, vs1, vs2, vl) |
  | Yes     | No  | Yes | vmacc_vv_i8m1_tamu(mask, vd, vs1, vs2, vl) |
  | Yes     | Yes | No  | vmacc_vv_i8m1_tuma(mask, vd, vs1, vs2, vl) |
  | Yes     | Yes | Yes | vmacc_vv_i8m1_tumu(mask, vd, vs1, vs2, vl)<br>vmacc_vv_i8m1_m(mask, vd, vs1, vs2, vl)<sup>1</sup> |

- only mask policy
  - 7\. Vector Store and Mask load（vlm）
  - 11.8. Vector Integer Compare Instructions
  - 13.13. Vector Floating-Point Compare Instructions
  - 15.2. Vector count population in mask vcpop.m
  - 15.3. vfirst find-first-set mask bit
  - 15.4. vmsbf.m set-before-first mask bit
  - 15.5. vmsif.m set-including-first mask bit
  - 15.6. vmsof.m set-only-first mask bit

  | Masked? | TU? | MU? | Intrinsic |
  | ------- | --- | --- | --------- |
  | No      | N/A  | N/A | vmseq_vv_i8m1_b8(vs1, vs2, vl) |
  | Yes     | N/A  | No  | vmseq_vv_i8m1_b8_ma(mask, vs1, vs2, vl) |
  | Yes     | N/A  | Yes  | vmseq_vv_i8m1_b8_mu(mask, vd, vs1, vs2, vl)<br>vmseq_vv_i8m1_b8_m(mask, vd, vs1, vs2, vl)<sup>1</sup> |

- only tail policy
  - 11.4. Vector Integer Add-with-Carry / Subtract-with-Borrow Instructions
    - vadc.vvm, vadc.vxm, vadc.vim
    - vsbc.vvm, vsbc.vxm
  - 11.15. Vector Integer Merge Instructions
  - 11.16. Vector Integer Move Instructions
  - 13.15. Vector Floating-Point Merge Instruction
  - 13.16. Vector Floating-Point Move Instruction
  - 16.1. Integer Scalar Move Instructions
    - vmv.s.x
  - 16.2. Floating-Point Scalar Move Instructions
    - vfmv.s.f
  - 16.5. Vector Compress Instruction

  | Masked? | TU? | MU? | Intrinsic |
  | ------- | --- | --- | --------- |
  | No      | No  | N/A | vmerge_vvm_i8m1_ta(mask, vs1, vs2, vl)<br>vmerge_vvm_i8m1(mask, vs1, vs2, vl)<sup>1</sup> |
  | No      | Yes | N/A | vmerge_vvm_i8m1_tu(mask, vs1, vs2, vl) |

- ignore mask policy and ignore tail policy
  - 11.4. Vector Integer Add-with-Carry / Subtract-with-Borrow Instructions
    - vmadc.vvm, vmadc.vxm, vmadc.vim, vmadc.vv vmadc.vx, vmadc.vi
    - vmsbc.vvm, vmsbc.vxm, vmsbc.vv, vmsbc.vx
  - 15.1. Vector Mask-Register Logical Instructions
  - 16.1. Integer Scalar Move Instructions
    - vmv.x.s
  - 16.2. Floating-Point Scalar Move Instructions
    - vfmv.f.s

  | Masked? | TU? | MU? | Intrinsic |
  | ------- | --- | --- | --------- |
  | No      | N/A  | N/A | vmadc_vvm_i8m1_b8(vs1, vs2, carryin, vl) |

**Comment by nick-knight** [comment]
> only mask policy
>  7. Vector Store and Mask load（vlm）

I believe `vlm.v` and `vsm.v` are always `tu` and unmasked.

**Comment by nick-knight** [comment]
@kito-cheng I agree with your argument, but the API doc says, in reference to the legacy API:
> Reduction intrinsics will generate code using tail undisturbed policy unless vundefined() is passed to the dest argument.

So I think you are proposing a backwards incompatible change.

I am OK with this backwards incompatible change, since I disagreed with several of the old defaults (although I understood their motivation). Frankly, I propose deprecating the legacy API. Less aggressively, if we're willing to break backwards compatibility but insist on keeping the legacy intrinsic names, I would just redefine them to alias the (new) "agnostic" instrinsics (`_ta`, `_ma`, or `_tama` as applicable).

**Comment by nick-knight** [comment]
> Is there also no _ta intrinsic? That is to say, only have vmseq_vv_i8m1_b8 for nomask operation and leaving the decision of vsetvl's tail policy to the compiler?

Precisely. As you noted earlier, the spec says:
> Mask destination tail elements are always treated as tail-agnostic, regardless of the setting of `vta`.

Our consensus is that it would be confusing to the intrinsics programmer to have `tu` intrinsics for these when there is no guarantee that the tail will be undisturbed. And without `tu` as an option, `ta` is redundant, so we decided to omit it from the API. 

In terms of generating assembly, the compiler might choose `tu` or `ta`. For example, if the previous instruction uses `tu`, then the compiler might continue using `tu` for the `vmseq` --- even though it's not guaranteed to be tail-undisturbed --- in order to avoid an unnecessary change to `vtype` (a `vsetvli` instruction).

**Comment by nick-knight** [comment]
I'd like to expand on a point in my previous comment, that the meaning of `{t,m}{a,u}` changes subtly across the intrinsics/assembly interface. More generally, the `vtype` register is not explicitly exposed to the intrinsics programmer. This enables compiler optimizations, for example:

* The programmer could use a `tu` intrinsic, and the compiler is allowed to implement it by masking and `mu`. This might be worthwhile if the appropriate mask was already available and `tamu` was already set in `vtype`, since it would avoid a `vsetvli` instruction.

* the programmer could use a `ta` intrinsic, and the compiler could implement it with `tu`, knowing that "undisturbed is a valid implementation of agnostic". This might be worthwhile if `tu` was already set in `vtype`, since it would avoid a `vsetvli` instruction. 

Whether or not contemporary compilers choose to leverage these optimizations, or plan to do so, isn't relevant to this API discussion.

**Comment by lhtin** [comment]
@kito-cheng @nick-knight 
> I would suggest the semantic of redsum_vs_i8m1(vd, vs1, vs2, vl) and vmacc_vv_i8m1(vd, vs1, vs2, vl) should be ta rather than tu, although that could be optimize to ta by compiler in theory, but reduction and macc instruction might used as loop carried variable which result the def-use of the dest register are both tu, then it hard to optimized to ta.
>
> And the tail element are usually unused on most cast especially for reduction, so I think it would be great to set that to ta, and we already provide _tu variant, so user could use that explicitly using that.

We change the behavior of our GCC(compare with llvm) based on our experience with using intrinsics. So these intrinsics behave as you suggest in our internal GCC.  **And if the `redsum_vs_i8m1_i8m1(vd, vs1, vs2, vl)` be `ta`, then vd parameter is not necessary. I think the breaking change of removing the vd parameter of the `redsum_vs_i8m1_i8m1` is necessary.**

**Comment by lhtin** [comment]
@nick-knight 

> I believe `vlm.v` and `vsm.v` are always (EDIT ~`tu`~) `ta` and unmasked.

You are right. Thank you for your review.

So move `vlm` and `vsm` to `ignore mask policy and ignore tail policy` category.

**Comment by lhtin** [comment]
Is it `tu` or `ta` for these `_m` legacy intrinsics(e.g. `vmacc_vv_i8m1_m`)? I think `ta` is more commonly used.

**Comment by zakk0610** [comment]
We will make a PR for these new set of API in next week to make anything clear, sorry for the inconvenience.

**Comment by nick-knight** [comment]
Thanks @zakk0610, I agree a PR would help us review this more efficiently. I will hold off on further comments.

**Comment by lhtin** [comment]
Looking forward to the new PR, thanks.

**Comment by zhongjuzhe** [comment]
@kito-cheng  @zakk0610. Hi, Can you tell me redsum_vs_i8m1 api is going to be redsum_vs_i8m1(vd, vs1, vs2, vl) or redsum_vs_i8m1(vs1, vs2, vl) ? The argument is different. I want to confirm about this. Thank you.

**Comment by zakk0610** [comment]
Please look at https://github.com/riscv-non-isa/rvv-intrinsic-doc/pull/137, we could have discussion there.

**Comment by eopXD** [comment]
Closing this issue since https://github.com/riscv-non-isa/rvv-intrinsic-doc/issues/47 have landed. Thanks everyone for all the efforts.
