### ISSUE TITLE
Question about tu intrinsics

### ISSUE THREAD

**Issue by zhongjuzhe** [riscv-non-isa/rvv-intrinsic-doc#124]
vint16mf4_t vwadd_vv_i16mf4_tu (vint8mf8_t dest, vint8mf8_t op1, vint8mf8_t op2, size_t vl);
This intrinsic add "dest" argument which is "vint8mf8_t " datatype, why it is not "vint16mf4_t" datatype?

**Comment by Hsiangkai** [comment]
My fault. I will fix it. Thanks.

**Comment by Hsiangkai** [comment]
https://github.com/riscv-non-isa/rvv-intrinsic-doc/pull/125
