### ISSUE TITLE
Typo in Vector Single-Width Integer Multiply-Add Operations

### ISSUE THREAD

**Issue by kuanlinchentw** [riscv-non-isa/rvv-intrinsic-doc#127]
Hi,
In rvv-intrinsic-api.md:[12.13. Vector Single-Width Integer Multiply-Add Operations](https://github.com/riscv-non-isa/rvv-intrinsic-doc/blob/master/rvv-intrinsic-api.md#instructions-21), I think the instruction vmacc_{vv,vx} should be vmacc.{vv,vx}.
And vnmsac_{vv,vx}, vmadd_{vv,vx}, vnmsub_{vv,vx} have the same issue.

**Comment by eopXD** [comment]
Thank you for spotting the typo. Mind sending a PR?

**Comment by eopXD** [comment]
Resolved in #128 .
