### ISSUE TITLE
Is it lack the `vmacc_vv_<ty>_tu` intrinsics in `intrinsic_funcs.md`?

### ISSUE THREAD

**Issue by lhtin** [riscv-non-isa/rvv-intrinsic-doc#129]
Hi,

Is it lack the `vmacc_vv_<ty>_tu` intrinsics in `intrinsic_funcs.md`, but should be supported according to [Tail Policy in the Intrinsics (rvv-intrinsic-rfc.md)](https://github.com/riscv-non-isa/rvv-intrinsic-doc/blob/master/rvv-intrinsic-rfc.md#tail-policy-in-the-intrinsics) of multily-add intrinsics? The same of vector reduction intrinsics.

Best regards,
Tin

**Comment by zakk0610** [comment]
Yes, you are right. We will fix it later, thanks!

**Comment by lhtin** [comment]
@zakk0610 And the vcompress, vslide[down|up], vmv.s.x intrinsics aslo lack the `_tu` intrinsic. All missing includes:

```
# 11.13. Vector Single-Width Integer Multiply-Add Instructions
vmacc
vnmsac
vmadd
vnmsub

# 11.14. Vector Widening Integer Multiply-Add Instructions
vwmaccu
vwmacc
vwmaccsu
vwmaccus

# 13.6. Vector Single-Width Floating-Point Fused Multiply-Add Instructions
vfmacc
vfnmacc
vfmsac
vfmadd
vfmsub
vfnmsub

# 13.7. Vector Widening Floating-Point Fused Multiply-Add Instructions
vfwmacc
vfwnmacc
vfwmsac
vfwnmsac

# 14.1. Vector Single-Width Integer Reduction Instructions
vredsum
vredmaxu
vredmax
vredminu
vredmin
vredand
vredor
vredxor

# 14.2. Vector Widening Integer Reduction Instructions
vwredsumu
vwredsum

# 14.3. Vector Single-Width Floating-Point Reduction Instructions
vfredosum
vfredusum
vfredmax
vfredmin

# 14.4. Vector Widening Floating-Point Reduction Instructions
vfwredosum
vfwredusum

# 16. Vector Permutation Instructions
vmv.s.x
vfmv.s.f
vslideup
vslidedown
vcompress
```

**Comment by eopXD** [comment]
https://github.com/riscv-non-isa/rvv-intrinsic-doc/issues/47 have updated a new batch of policy intrinsics. I think the issue is resolved now and we can close the issue :)
