### ISSUE TITLE
Make the tuple type API for segment load store as compiler optional feature

### ISSUE THREAD

**Issue by zakk0610** [riscv-non-isa/rvv-intrinsic-doc#139]
https://github.com/riscv-non-isa/rvv-intrinsic-doc/pull/137#issuecomment-1061338688
https://github.com/riscv-non-isa/rvv-intrinsic-doc/pull/137#issuecomment-1061363901

Below is @kito-cheng's proposal for the segment load/store API:

Include both API flavor in spec, but mark tuple type style API as optional, and defined some marco to let user check __riscv_rvv_tuple_type if compiler has supported.

And non-tuple type style API / new API are mandatory, I believe implement that via tuple type style API like that is feasible, and @rjiejie has implemented this approach in the past https://github.com/riscv-collab/riscv-gcc/pull/307:

void vlseg2e8_v_i8mf4 (vint8mf4_t *v0, vint8mf4_t *v1, const int8_t *base, size_t vl)
{
  vint8mf4x2_t vt = vcreate_i8mf4x2 (v0, v1);
  vlseg2e8_v_i8mf4x2 (vt, vase, v0);
}

**Comment by nick-knight** [comment]
We will probably need to revert https://github.com/riscv-non-isa/rvv-intrinsic-doc/pull/98 too, tagging these functions appropriately.

**Comment by lhtin** [comment]
Maybe it's necessary to change the marco name `__riscv_rvv_tuple_type` to `__riscv_v_tuple_type`, because it is unified with [`__riscv_v_intrinsic_overloading`](https://github.com/riscv-non-isa/rvv-intrinsic-doc/blob/master/rvv-intrinsic-rfc.md#overloaded-interface).

**Comment by kito-cheng** [comment]
@lhtin Yeah, `__riscv_v_tuple_type` seems like better naming, thank for your suggestion !

**Comment by eopXD** [comment]
Multiple issues have raised request for tuple types and size-less struct and it all boils down if the compiler is able to implement them...

Redirecting other existing issues(#13, #17 , #110 , #154) here for this issue to be the placeholder to discuss on the problem after the v1.0 release.
