### ISSUE TITLE
Move mask argument positions to first for merge intrinsic function.

### ISSUE THREAD

**Issue by zakk0610** [riscv-non-isa/rvv-intrinsic-doc#140]
@nick-knight 's [perspective ](https://github.com/riscv-non-isa/rvv-intrinsic-doc/issues/126#issuecomment-1048048817) convince me, but if we make the changed, how do users know that when they should use the new one API or old one.

It seems like a general question like, if we decide to change the interface which would break the backward compatible, how to let users to known about that.

**Comment by eopXD** [comment]
I think formalizing rvv intrinsic releases will solve the problem.

We can have the new ones and old ones co-exist with deprecation warnings by the compiler. Then remove them in the next release.

**Comment by eopXD** [comment]
Since we may already have users on the current intrinsics and don't want to break backward compatibility, maybe we would prefer to extend more intrinsics as your request specifies than replacing them?

Let's hold this for discussion after the v1.0 release?
