### ISSUE TITLE
question about C++ overloaded functions of vwadd/vwsub/vfwadd/vfwsub......

### ISSUE THREAD

**Issue by zhongjuzhe** [riscv-non-isa/rvv-intrinsic-doc#150]
When I am implementing C++ overloaeded functions in GCC. I saw there is inconsistency between `vfwadd` and `vfwmul`. For C++ overloaded functions. `vfwmul` can be resolved into `vfwmul.vv` or `vfwmul.vf` instructions according to the arguments. So it make sense
that C++ overloaded functions define the intrinsic like this `vfloat32mf2_t vfwmul (vfloat16mf4_t op1, vfloat16mf4_t op2, size_t vl);`.
But for `vfwadd`, the intrinsic are not using this same rule. I saw there are definitions like
`vfloat32mf2_t vfwadd_vv (vfloat16mf4_t op1, vfloat16mf4_t op2, size_t vl);`
`vfloat32mf2_t vfwadd_vf (vfloat16mf4_t op1, float16_t op2, size_t vl);`
`vfloat32mf2_t vfwadd_wv (vfloat32mf2_t op1, vfloat16mf4_t op2, size_t vl);`
`vfloat32mf2_t vfwadd_wf (vfloat32mf2_t op1, float16_t op2, size_t vl); `. I think the suffix `_vv` `_vf` `wv` `wf` are redundant. It can be resolved to different instructions according to different argument too. Can anyone tell me the story about why the document define these C++ functions?

**Comment by zakk0610** [comment]
`vfwmul` have no `wv` or `wf` operation, so they do not have https://github.com/riscv-non-isa/rvv-intrinsic-doc/blob/master/rvv-intrinsic-rfc.md#widening-vector-scalar-arithmetic-instructions-for-vxwx-and-vfwf-cases
problem which `vfwadd`/`vfadd` have.

**Comment by zhongjuzhe** [comment]
> `vfwmul` have no `wv` or `wf` operation, so they do not have https://github.com/riscv-non-isa/rvv-intrinsic-doc/blob/master/rvv-intrinsic-rfc.md#widening-vector-scalar-arithmetic-instructions-for-vxwx-and-vfwf-cases problem which `vfwadd`/`vfadd` have.

OK, Thanks for your reply.
I have a another question about C++ overloaded functions in the new-policy api.
I saw `vint8mf8_t vmv_s_ta (int8_t src, size_t vl);` and `vint8mf4_t vmv_s_ta (int8_t src, size_t vl);` these 2 C++ functions.
I think in this case, it can not be overloaded. Am I wrong about this?

**Comment by zakk0610** [comment]
Yes, you are right. We are still working on implementation in clang and would fix all bugs in the policy PR later.
The another bug is reduction tam need to remove the merge operand.
```
int8m1_t vredsum_vs_i8mf8_i8m1_tam (vbool64_t mask, vint8m1_t merge, vint8mf8_t vector, vint8m1_t scalar, size_t vl); // incorrect
int8m1_t vredsum_vs_i8mf8_i8m1_tam (vbool64_t mask, vint8mf8_t vector, vint8m1_t scalar, size_t vl); // correct
```
