### ISSUE TITLE
Convolution and Maxpool Operation in vector mode

### ISSUE THREAD

**Issue by Mousavikia** [riscv-non-isa/rvv-intrinsic-doc#152]
Hi guys I really tried to write a convolutional neural network code in vector intrinsic but unfortunately I have problem implementing max pool and convolution function. Just to declare for maxpooling the function is like this:
![MaxpoolSample2](https://user-images.githubusercontent.com/96676046/164205327-961a6b34-9ff8-4fc7-a3fd-b88e277424b1.png)
I know `vredmax` can help but the strides (taking a 2*2 window and comparing) really confuses me..
And for convolution:
![Understand-tf nn_ conv2d-Compute-a-2-D-Convolution-in-TensorFlow-660x264](https://user-images.githubusercontent.com/96676046/164205716-891f6b3e-32f3-475e-a907-91197558bd08.png)
And for this I know `vmacc` can help but again like maxpooling I am lost...
Any help or suggestions?

**Comment by eopXD** [comment]
I think this is question is not related to RVV intrinsic discussions but just asking for SIMD programming advices.

**Comment by Mousavikia** [comment]
Thank you @zakk0610 I actually utilized Im2col but in my specific core it gives worse latency than scaler version. I first utilize a normal scaler function for im2col then for convolution since my filters are `2*2` I utilize `vl=4` and then use `vwmul` and `vredsum` to get the result and for maxpool it is kind of a same procedure but I utilize `vredmax` in this case. Is there any better way? I have kind of big arrays so realizing im2col with scaler functions use lot of memory and I think that function is the bottleneck for my runtime... Can you suggest a better approach?
