### ISSUE TITLE
Relax constaints on sizeless types

### ISSUE THREAD

**Issue by QuarticCat** [riscv-non-isa/rvv-intrinsic-doc#154]
I don't know if it is proper to open this issue here.

Currently, Clang doesn't allow us to use RVV intrinsic types inside `struct`. The same as SVE intrinsic types. However, I noticed that Rust does allow sizeless types in structs, with a constraint that it must be the last field of the struct. Can we also implement this in C++? I think this feature is very useful for those wrapper libraries, and makes RVV intrinsic easier to use.

**Comment by eopXD** [comment]
This is a duplicate question with #139. Marking this as duplicate and closing.

This is definitely a topic we will dwell on, but the intrinsic API needs a v1.0 release now. So the discussion will be held later.
