### ISSUE TITLE
Mask Load/Store Intrinsic functions not found

### ISSUE THREAD

**Issue by xiaorui-yin** [riscv-non-isa/rvv-intrinsic-doc#163]
Hi all, I would like to ask how to use mask load/store intrinsic functions, because currently the function page is empty (404).

**Comment by hdelassus** [comment]
Hi, I think you are looking for [this page](https://github.com/riscv-non-isa/rvv-intrinsic-doc/blob/master/intrinsic_funcs/08_vector_mask_functions.md#vector-mask-loadstore-functions). Some links appear to be broken.

**Comment by topperc** [comment]
Attempted fix https://github.com/riscv-non-isa/rvv-intrinsic-doc/pull/164

**Comment by xiaorui-yin** [comment]
Thank you very much!
