### ISSUE TITLE
How the column-wise reading done in rvv_matmul.c ?

### ISSUE THREAD

**Issue by balaji-ch** [riscv-non-isa/rvv-intrinsic-doc#169]
In 
https://github.com/riscv-non-isa/rvv-intrinsic-doc/blob/master/examples/rvv_matmul.c

` double *ptr_b = &b[j][0];` 
`vfloat64m1_t vec_b = vle64_v_f64m1(ptr_b, vl);`

Here the ptr_b should be read in column-wise but the stride seems to be unit wise making it row wise read.

Is this correct ?

**Comment by eopXD** [comment]
Just as described in the comment of the code, it is doing matrix multiplication of `A[n][o], B[m][o] --> C[n][m]`
