### ISSUE TITLE
Question about load mask intrinsics

### ISSUE THREAD

**Issue by RuHungLee** [riscv-non-isa/rvv-intrinsic-doc#215]
I would like to use RVV intrinsics to load an immediate value into a mask register ( v0 ). However, in the specification, I only see intrinsics for loading values from memory into a mask register ( vlm ). Is there an intrinsic available for loading an immediate value into a mask register?

**Comment by nick-knight** [comment]
Once we resolve https://github.com/riscv-non-isa/rvv-intrinsic-doc/issues/156, we will have more options.

**Comment by eopXD** [comment]
We do have the type-cast intrinsics now. I assume the problem should be resolved.
