### ISSUE TITLE
Why use vleff instead of vle to implement the strncpy

### ISSUE THREAD

**Issue by zfcfuture** [riscv-non-isa/rvv-intrinsic-doc#217]
Excuse me, i have a question that is not very relevant to this project.
What I don't understand is that `vleff` instruction can also implement the `strncpy( )`, so why choose `vleff` instruction to implement it? What is the unique advantage of `vleff` instruction.
thank you very much & looking forward to your reply

**Comment by eopXD** [comment]
Underlying data under src is unknown, `vleff` provides the actual valid length here and allows the loop to exit successfully, which `vle` can't.

The assembly version here [0] and the v-spec [1] should help you understand why vleff is used here.

[0] https://github.com/riscv/riscv-v-spec/blob/master/example/strncpy.s
[1] https://github.com/riscv/riscv-v-spec/blob/master/v-spec.adoc
