### ISSUE TITLE
Maskedoff parameters in "xu" prototypes

### ISSUE THREAD

**Issue by fuhle044** [riscv-non-isa/rvv-intrinsic-doc#228]
Hi, I am trying to get my head around why the xu intrinsics have maskedoff parameters since there is no mask parameter. Is this simply an error in the auto-generated prototypes or am I missing something subtle or obvious?

**Comment by hdelassus** [comment]
Presumably you meant `tu` intrinsics. I've seen these parameters also be called `merged` instead of `maskedoff`. They basically tell the compiler which destination to write to with tail undisturbed policy.
As an example, see how this snippet [is compiled](https://godbolt.org/z/7jz3Y568s):
```c++
#include <riscv_vector.h>

vfloat64m1_t foo(vfloat64m1_t &x, vfloat64m1_t y, vfloat64m1_t z, size_t vl) {
    // x stored at (a0), y in v8, z in v9.
    x = __riscv_vfadd_tu(y, z, z, vl);
    y = __riscv_vfmul_tu(y, x, x, vl);
    return y;
}
```
