### ISSUE TITLE
question about intrinsic naming 

### ISSUE THREAD

**Issue by PPParticle** [riscv-non-isa/rvv-intrinsic-doc#231]
i don't understand the reason why all intrinsic apis are added "__riscv" prefix. Typing more letters seems more troublesome for programmers.

**Comment by PPParticle** [comment]
Also, i think previous naming rule is clear and easy to understand.

**Comment by topperc** [comment]
Primarily for the same reason C++ has namespaces. Adding the "__riscv" makes it less likely to collide with user variable names or names from other libraries a user might be using.
