### ISSUE TITLE
vwcvt(u).x.x.v intrinsics are mis-categorized

### ISSUE THREAD

**Issue by topperc** [riscv-non-isa/rvv-intrinsic-doc#239]
In rvv-intrinsic-api.md these intrinsics are listed as being in `11.2. Vector Widening Integer Add/Subtract Operations`, but they are not included in the Intrinsic Function list file that section points to.

They are instead listed in the function list for `13.18. Widening Floating-Point/Integer Type-Convert Operations`

cc: @nick-knight

**Comment by eopXD** [comment]
Yes I guess we should try our best to resemble the sequence from v-spec.
