### ISSUE TITLE
Will CSR API be removed?

### ISSUE THREAD

**Issue by zhongjuzhe** [riscv-non-isa/rvv-intrinsic-doc#246]
I saw fixed-point and floating-point rounding API are merged.

But I saw:

Read/Write URW vector CSRs
enum RVV_CSR {
  RVV_VSTART = 0,
  RVV_VXSAT,
  RVV_VXRM,
  RVV_VCSR,
};

unsigned long __riscv_vread_csr(enum RVV_CSR csr);
void __riscv_vwrite_csr(enum RVV_CSR csr, unsigned long value);

unsigned long __riscv_vlenb();

Will they be removed?

**Comment by eopXD** [comment]
There are the exception flag intrinsics not yet to be modeled, but since the intrinsics are in our future plan. I think they should be removed.
