### ISSUE TITLE
Double Check about RVV Float Point Honor FRM

### ISSUE THREAD

**Issue by Incarnation-p-lee** [riscv-non-isa/rvv-intrinsic-doc#250]
Hi Eop,

Just go thru all the float point FRM intrinisc API and locate some of them that may need double confirmation with you, for the FRM is honored or not.

* [No] vfrsqrt7
* [No] vfwcvt.f.x.v
* [No] vfwcvt.f.xu.v
* [No] vfwcvt.f.f.v
* vfredosum.vs
* vfredusum.vs
* vfwredosum.vs 
* vfwredusum.vs 

CC @kito-cheng and @zhongjuzhe for awareness.

Pan

**Comment by topperc** [comment]
I think vf(w)redsum uses rounding mode. The others do not.

**Comment by Incarnation-p-lee** [comment]
Yes, vfw from INT to FP may never lose precisions, thus rounding is not required up to a point.

**Comment by eopXD** [comment]
Floating-point rounding mode intrinsics are added now. Closing this issue.
