### ISSUE TITLE
Examples use arithmetic on `void*`, which isn't allowed by the c standard

### ISSUE THREAD

**Issue by camel-cdr** [riscv-non-isa/rvv-intrinsic-doc#252]
Examples, specifically rvv_memcpy,  use arithmetic on `void*`, which isn't allowed by the c standard, see: https://stackoverflow.com/questions/3523145/pointer-arithmetic-for-void-pointer-in-c#3524270

**Comment by nick-knight** [comment]
Feel free to submit a PR. These examples are not a normative part of the spec, so the task group is treating them as lower priority, to focus our limited (volunteer) resources on reaching API freeze/ratification.

**Comment by camel-cdr** [comment]
👍 I'll look into it when I've got the time
