### ISSUE TITLE
Issue： wrong type

### ISSUE THREAD

**Issue by unicornx** [riscv-non-isa/rvv-intrinsic-doc#259]
https://github.com/riscv-non-isa/rvv-intrinsic-doc/releases/tag/draft-20230811-a810011071e9e2f630450f01f5fdc9a9ccc3e3be

7.1. Integer types

Table 1. Integer types：Should be “mf4”.
![image](https://github.com/riscv-non-isa/rvv-intrinsic-doc/assets/2476165/f8c116d9-8f03-448a-8d1f-82a20ce672d7)

Table 1. Integer types，should be "m8"
![image](https://github.com/riscv-non-isa/rvv-intrinsic-doc/assets/2476165/1b7e90c1-5c1c-444b-8d89-b658a38122a0)

Table 2. Floating-point types， Should be “mf4”.
![image](https://github.com/riscv-non-isa/rvv-intrinsic-doc/assets/2476165/521465b3-20ab-4e12-b76e-0a05a07afaf7)

**Comment by punkyc** [comment]
Table 2 last column seems have same problems.

**Comment by eopXD** [comment]
This should be fixed in [c68122f](https://github.com/riscv-non-isa/rvv-intrinsic-doc/pull/261/commits/c68122f6fc762eee11a82a5238ce7bdf9a8060ea).
