### ISSUE TITLE
why vslideup intrinsics have dest parameter

### ISSUE THREAD

**Issue by huyuantao-ultrarisc** [riscv-non-isa/rvv-intrinsic-doc#265]
Hi, I am confused that vslideup intrinsics have dest parameter and vslidedown intrinsics don't have. Is dest parameter redundant?

![image](https://github.com/riscv-non-isa/rvv-intrinsic-doc/assets/130338111/64a1de94-54a4-47c1-8354-06b12df9f054)

**Comment by topperc** [comment]
The dest parameter is there to support the "unchanged" part of this from the spec.

```
                  0 <  i < max(vstart, OFFSET)  Unchanged
max(vstart, OFFSET) <= i < vl                   vd[i] = vs2[i-OFFSET] if v0.mask[i] enabled
                 vl <= i < VLMAX                Follow tail policy
```

**Comment by kito-cheng** [comment]
Close since I believe Craig has answered :)
