### ISSUE TITLE
Question about segment load/store of rvv-v0p10-compatible-headers

### ISSUE THREAD

**Issue by xl0714** [riscv-non-isa/rvv-intrinsic-doc#273]
Hi, @eopXD :
The current form is:

#define vlseg2e8_v_i8m1(...) __riscv_vlseg2e8_v_i8m1(__VA_ARGS__)
#define vlseg2e8_v_i8m1_m(...) __riscv_vlseg2e8_v_i8m1_tumu(__VA_ARGS__)
#define vlseg2e8_v_i8m1_tu(...) __riscv_vlseg2e8_v_i8m1_tu(__VA_ARGS__)
#define vlseg2e8_v_i8m1_ta(...) __riscv_vlseg2e8_v_i8m1(__VA_ARGS__)
#define vlseg2e8_v_i8m1_tuma(...) __riscv_vlseg2e8_v_i8m1_tum(__VA_ARGS__)
#define vlseg2e8_v_i8m1_tumu(...) __riscv_vlseg2e8_v_i8m1_tumu(__VA_ARGS__)
#define vlseg2e8_v_i8m1_tama(...) __riscv_vlseg2e8_v_i8m1_m(__VA_ARGS__)
#define vlseg2e8_v_i8m1_tamu(...) __riscv_vlseg2e8_v_i8m1_mu(__VA_ARGS__)

However, gcc no longer supports non-tuple segment load/store. Should we consider mapping non-tuple to tuple?

**Comment by eopXD** [comment]
The v0p10 compatible header was intended to support transition from v0.10 to v0.11. The tuple type segment load/store was introduced in v0.12. We currently do not have a compatible header / patch in the upstream to support compatibility for v0.11 -> v0.12.

This is a duplicate issue to #255. As I mentioned in that thread, I think continue-ing the compatibility support in the upstream trunk may not be beneficial for the ecosystem.
