### ISSUE TITLE
Create bibliography from reference section

### ISSUE THREAD

**Issue by kersten1** [riscv-non-isa/rvv-intrinsic-doc#312]
Create a bibliography that follows RISC-V standards by using the existing Reference section in intrinsics doc.

**Comment by rofirrim** [comment]
Hi @kersten1 do you have bandwidth for this?

I can take over it if needed.

**Comment by kersten1** [comment]
@rofirrim Please feel free! I was waiting for the vector PR to be merged and nowI keep getting distracted by other stuff.

**Comment by rofirrim** [comment]
> @rofirrim Please feel free! I was waiting for the vector PR to be merged and nowI keep getting distracted by other stuff.

Thanks!
