### ISSUE TITLE
Mismatched bfloat16 autogenerated files

### ISSUE THREAD

**Issue by dzaima** [riscv-non-isa/rvv-intrinsic-doc#335]
Running `make bf16-all` I get it generating incorrect reinterpret instructions like `__riscv_reinterpret_v_bf16m8_i16m8`.

Note the lack of `v` prefix there, which matches no `v` in `["reinterpret"]` in `bfloat16_inst.py`.

**Comment by kito-cheng** [comment]
@4vtomat could you take a look for this issue?

**Comment by dzaima** [comment]
Somewhat-relatedly, `__riscv_vfwmacc*_vf_` intrinsics (not just bfloat16 ones; and other float multiply-add intrinsics too) name their scalar arguments `vs1` where I think it should be `rs1`. This appears to have been the case for a while.

**Comment by 4vtomat** [comment]
Thanks @dzaima , let me take this!
