### ISSUE TITLE
Should f16 vrgather/vcompress be supported for f16 with Zvfhmin? bf16 with Zvfbfmin?

### ISSUE THREAD

**Issue by topperc** [riscv-non-isa/rvv-intrinsic-doc#350]
clang supports f16 vrgather/vcompress with Zvfh, but the required instruction are part of the base vector spec. It could work with Zvfhmin like load/store.

clang doesn't support bf16 vrgather at all.

CC: @kito-cheng @rofirrim

**Comment by rofirrim** [comment]
Agreed.
