### ISSUE TITLE
Should f16 vundefined/lmul_ext/lmul_trunc/vget/vset/vcreate be support with Zvfhmin

### ISSUE THREAD

**Issue by topperc** [riscv-non-isa/rvv-intrinsic-doc#351]
If I'm reading the clang source right these operations only support f16 with Zvfh. I think they could be supported with Zvfhmin.

These operations are supported for bf16 with Zvfbfmin.

CC: @kito-cheng @rofirrim

**Comment by rofirrim** [comment]
Indeed, I guess we want f16 to be consistent with bf16 here.
