### ISSUE TITLE
How to perform bit shift operations on mask type (such as vbool16_t) through intrinsic functions？

### ISSUE THREAD

**Issue by cocacola-wing** [riscv-non-isa/rvv-intrinsic-doc#380]
Hi, there!

I used a mask type` vbool16_t` to represent the carry bit of addition, and now I need to shift it left to propagate the carry. But I can't find the corresponding intrinsic function, not even the intrinsic function to convert `vbool16_t` to `uint16_t`. 

I saw someone mentioned it, but it was in assembly code. 
[Rotate and shift vector mask bits](https://github.com/riscvarchive/riscv-v-spec/issues/919)

Is it necessary to add some pseudo intrinsics to achieve it?

**Comment by topperc** [comment]
You can use `__riscv_vreinterpret_v_b16_u64m1` to cast from `vbool16_t` to `vuint64m1_t` then you can use __riscv_vsrl.

**Comment by cocacola-wing** [comment]
> You can use `__riscv_vreinterpret_v_b16_u64m1` to cast from `vbool16_t` to `vuint64m1_t` then you can use __riscv_vsrl.

Oh! I didn't notice the super `vreinterpret`. Thank you so much!

**Comment by cocacola-wing** [comment]
It works! Thanks again!
