### ISSUE TITLE
Support more util functions for vector status register.

### ISSUE THREAD

**Issue by JerryShih** [riscv-non-isa/rvv-intrinsic-doc#45]
Currently, we have "vreadvl()" to get the vl, we could have more util functions for "mstatus", "vlenb", "vstart" and other status register.

**Comment by arcbbb** [comment]
You could propose a simple implementation like https://github.com/riscv/rvv-intrinsic-doc/issues/36

**Comment by eopXD** [comment]
Exposing `vlenb` may be a feature to consider, but there is no benefit to expose `mstatus` and `vstart`. Let us revisit this after v1.0.

**Comment by eopXD** [comment]
Revisiting this issue after a year now...

`VLEN` is now exposed.

The `vstart` CSR is currently not exposed to the intrinsics programmer, and the intrinsics have the semantics of `vstart = 0`. So I think it would be strange for us to expose control to `vstart`. Additionally, support for positive `vstart` values is implementation -defined; thus, portable application software should not set `vstart > 0`.

Other than `vxsat` and `fflag` that is left to be exposed, I don't think `vstart` and `mstatus` would be our consideration. Please open up another issue if you have a strong demand to this feature.
