### ISSUE TITLE
Approximate reciprocal/rsqrt

### ISSUE THREAD

**Issue by jan-wassenberg** [riscv-non-isa/rvv-intrinsic-doc#58]
It seems that vfrsqrte7 and vfrece7 from v0.9 are not yet added, perhaps pending the naming discussion in https://github.com/riscv/riscv-v-spec/issues/601 ?

**Comment by zakk0610** [comment]
`vfrsqrte7` and `vfrece7` are not the 0.9 instruction.
https://github.com/riscv/riscv-v-spec/blob/0.9/v-spec.adoc

**Comment by jan-wassenberg** [comment]
Agreed, they are in the [1.0 draft](https://github.com/riscv/riscv-v-spec/blob/master/v-spec.adoc#added-reciprocal-and-reciprocal-square-root-estimate-instructions), sorry I was unclear (should have written "added since/changed from v0.9", not "from").

**Comment by jan-wassenberg** [comment]
Ah, I see that this repo is currently targeting 0.9 only. Is the plan to update to 1.0 only after it is ratified?

**Comment by zakk0610** [comment]
Sorry, what do you mean?
This repo has a [tag](https://github.com/riscv/rvv-intrinsic-doc/tree/v0.9) for v0.9 and master branch is targeting on 1.0 draft. 
You can find [`vfrsqrte7`](https://github.com/riscv/rvv-intrinsic-doc/blob/master/rvv_intrinsic_funcs/08_vector_floating-point_functions.md#vector-floating-point-reciprocal-square-root-estimate-functions) and [`vfrece7`](https://github.com/riscv/rvv-intrinsic-doc/blob/master/rvv_intrinsic_funcs/08_vector_floating-point_functions.md#vector-floating-point-reciprocal-estimate-functions) in master branch.

**Comment by kito-cheng** [comment]
> Ah, I see that this repo is currently targeting 0.9 only. Is the plan to update to 1.0 only after it is ratified?

Yeah, we are plan to upgrade that to 1.0 once it ratified or tagged, but the time is much later than our expect...

**Comment by kito-cheng** [comment]
Oh, I forgot @zakk0610 has been update before :P

**Comment by kito-cheng** [comment]
Seems like we forgot to update the doc about the version info :P
https://github.com/riscv/rvv-intrinsic-doc/pull/59

**Comment by zakk0610** [comment]
> Ah, I see that this repo is currently targeting 0.9 only. Is the plan to update to 1.0 only after it is ratified?

oh, sorry. I forget to update version info.

**Comment by jan-wassenberg** [comment]
Thank you @kito-cheng and @zakk0610  for clarifying the version number and plan :)

**Comment by eopXD** [comment]
The ratified v-spec v1.0 don't include these instructions. This issue is no longer valid.
