### ISSUE TITLE
Rename maskedoff operand to merged operand

### ISSUE THREAD

**Issue by zakk0610** [riscv-non-isa/rvv-intrinsic-doc#70]
For masked operations, users could pass `maskedoff` operand to setup both inactive and tail elements.
Avoiding to confusing, I think maybe we should call it as merged operand.
So the spec will update from
```
vint8m1_t vle8_v_i8m1_m (vbool8_t mask, vint8m1_t maskedoff, const int8_t *base, size_t vl);
```
to
```
vint8m1_t vle8_v_i8m1_m (vbool8_t mask, vint8m1_t merged, const int8_t *base, size_t vl);
```

Any ideas?

**Comment by eopXD** [comment]
Zakk's PR have resolved this in all policy intrinsic functions. For non-policy intrinsics follow (ta, mu) (except for reduction operations, but we call them `dest` in the parameters). Therefore I think this issue is now resolved and can be closed.
