### ISSUE TITLE
Vector Mask Load/Store Functions

### ISSUE THREAD

**Issue by mp-17** [riscv-non-isa/rvv-intrinsic-doc#75]
Hello everyone,

It seems that the `rvv-intrinsic` branch of the `riscv-toolchain` does not recognize vector mask load/store functions (e.g., `vle1_v_b1`), even if they are listed in `rvv-intrinsic-doc/intrinsic_funcs.md`.

I guess the best way to load a usable mask vector from memory is still this one (https://github.com/riscv/rvv-intrinsic-doc/issues/61#issuecomment-762965707), right?

Thanks a lot for the work,
Matteo

**Comment by eopXD** [comment]
We have `vlm_v` and `vsm_v` in the intrinsic now that matches the v-spec.
