### ISSUE TITLE
Rename vle1/vse1 intrinsics to vlm/vsm to match V extension draft

### ISSUE THREAD

**Issue by topperc** [riscv-non-isa/rvv-intrinsic-doc#79]
The current V extension draft has renamed these instructions. The assembler will accept both names. We should do what we can to encourage the new names in the intrinsics. But we might have to support both names like the assembler.

**Comment by Hsiangkai** [comment]
Should we have any version control about this document? vlm/vsm are not belong to v0.10.

**Comment by zakk0610** [comment]
Yes, so I added a v0.10 tag.
https://github.com/riscv/rvv-intrinsic-doc/tree/v0.10

**Comment by eopXD** [comment]
Issue is resolved and implemented. Closing the issue.
